[build]
  command = "npm run build"
  publish = "dist"
  [build.environment]
    NODE_ENV = "production"
    NODE_VERSION="14"
    NPM_CONFIG_AUDIT = "false"
    NPM_CONFIG_PRODUCTION = "false"
    NPM_CONFIG_OPTIONAL = "false"
    NPM_FLAGS = "--ignore-scripts"
  [build.processing]
    skip_processing = true

[[redirects]]
  from = "https://www.cakedaze.nl/"
  to = "https://cakedaze.nl/"
  force = true
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
